targets:
  $default:
    builders:
      json_serializable:
        generate_for:                  # ✅ Correct place
          include:
            - lib/**.dart
        options:

          explicit_to_json: true
          field_rename: snake